version: '3.8'

services:
  sql-server-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=TechMoveSql2026!
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql

  glms-backend-api:
    build:
      context: .
      dockerfile: TechMove.Glms.Api/Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=Server=sql-server-db,1433;Database=TechMoveGlms;User Id=sa;Password=TechMoveSql2026!;TrustServerCertificate=True;
    ports:
      - "5269:8080"
    depends_on:
      - sql-server-db

  glms-frontend-web:
    build:
      context: .
      dockerfile: TechMove.Glms.Web/Dockerfile
    environment:
      - ApiBaseUrl=http://glms-backend-api:8080/
    ports:
      - "5255:8080"
    depends_on:
      - glms-backend-api
    volumes:
      - glms-uploads:/app/wwwroot/uploads

volumes:
  sqlserver-data:
  glms-uploads:

